#!/bin/bash

echo "-----------------------------------------------------------------"
echo "Create the vscode-server machine"
echo "-----------------------------------------------------------------"

# [x] Specific VM template configurations

# Proxmox
TEMPLATE=5124 # Ubuntu 24.04
VMID=3099 # 3003
TAGS=_vms,vscode,dev
MACHINE_NAME=VSCODE
START_ON_PVE_REBOOT=1

# KVM
RAM=12288
CORES=3
BRIDGE=vmbr1
VLAN=30
EXPAND_DISKIMAGE_SIZE=64G # 0G for no resize

#### Cloud Init
IP=192.168.30.200/24 #192.168.30.3
GW=192.168.30.1
DNS=192.168.30.1

#### required data
DATA=()
AUTOGENERATED_DATA=(VSCODE_PASSKEY)


# [x] Load common configs from the common scripts
echo "Load common configs from the common scripts"
source ../lib/common_vm_scripts.sh

# [x] Load common VM template configurations
create_retrive_common_variable_from_pass "default_domain"
MAIN_DOMAIN=$RETURN_VALUE
create_retrive_common_variable_from_pass "default_user"
DEFAULT_USER=$RETURN_VALUE
create_retrive_common_variable_from_pass "default_password_length"
DEFAULT_PASSWORD_LENGTH=$RETURN_VALUE
create_retrive_vm_autogenerated_variable_from_pass $VMID $DEFAULT_PASSWORD_LENGTH
USER_PASSWORD=$RETURN_VALUE

# [x] Load VM template configurations
load_vm_data $DATA $AUTOGENERATED_DATA 

# [x] Destroy the old VM if it exists
destroy_old_vm $VMID

# [x] Create new VM
create_new_vm

# [x] Start the VM template, wait it to start, and then execute the setup script
template_os_setup


#############################################################
echo "----------------------------------------------------------------------------------------"
echo "Done for $MACHINE_NAME VM ..."
echo "----------------------------------------------------------------------------------------"