#!/bin/bash

# Specific VM template configurations

# Proxmox
TEMPLATE=5212 # debian 12
VMID=2012
TAGS=_dmz,onlyoffice,groupwork
MACHINE_NAME=ONLYOFFICE
START_ON_PVE_REBOOT=1
STORAGE=local-zfs 

# KVM
RAM=12288
CORES=4
BRIDGE=vmbr1
VLAN=20
EXPAND_DISKIMAGE_SIZE=80G # 0G for no resize

#### Cloud Init
IP=192.168.20.3/24
GW=192.168.20.1
DNS=192.168.20.1

#### required data
VM_DATA=("MEGA_USERNAME" "MEGA_PASSWORD" "MEGA_WEBDAV_BACKUP" "MEGA_WEBDAV_WORKSPACE")
AUTOGENERATED_DATA=()


# Load common configs from the common scripts
echo "Load common configs from the common scripts"
source ../lib/common_vm_scripts.sh
vm_creation_steps