#!/bin/bash

# Specific VM template configurations

# Proxmox
TEMPLATE=5212 # debian 12
VMID=3099
TAGS=_dmz,moodle,education
MACHINE_NAME=MOODLE
START_ON_PVE_REBOOT=1
STORAGE=local-lvm 

# KVM
RAM=4096
CORES=2
BRIDGE=vmbr1
VLAN=30
EXPAND_DISKIMAGE_SIZE=10G # 0G for no resize

#### CLOUD-INIT
IP=192.168.30.201/24 
GW=192.168.30.1
DNS=192.168.30.1

#### REQUIRED-DATA
VM_DATA=("")
VM_AUTOGENERATED_DATA=("")


# Load common configs from the common scripts
echo "Load common configs from the common scripts"
source ../lib/common_vm_scripts.sh
vm_creation_steps