
#!/bin/bash

# Specific VM template configurations

# PROXMOX
TEMPLATE=5122 # Ubuntu 22.04
VMID=3003
TAGS=_vms,tunnels
MACHINE_NAME=tunnels
START_ON_PVE_REBOOT=1
STORAGE=local-zfs  

# KVM
RAM=512
CORES=1
BRIDGE=vmbr1
VLAN=30
EXPAND_DISKIMAGE_SIZE=0G # 0G for no resize

#### CLOUD-INIT
IP=192.168.30.3/24
GW=192.168.30.1
DNS=192.168.30.1

#### REQUIRED-DATA
VM_DATA=("CLOUDFLARE_TUNNEL_KEY", "TAILSCALE_AUTH_KEY")
VM_AUTOGENERATED_DATA=("")


# Load common configs from the common scripts
echo "Load common configs from the common scripts"
source ../lib/common_vm_scripts.sh
vm_creation_steps