#!/bin/bash

# Specific VM template configurations

# Proxmox
TEMPLATE=5212 # debian 12
VMID=2012
TAGS=_vms,vscode,dev
MACHINE_NAME=VSCODE
START_ON_PVE_REBOOT=1
STORAGE=local-lvm 

# KVM
RAM=8192
CORES=4
BRIDGE=vmbr1
VLAN=30
EXPAND_DISKIMAGE_SIZE=64G # 0G for no resize

#### CLOUD-INIT
IP=192.168.30.200/24 #192.168.30.3
GW=192.168.30.1
DNS=192.168.30.1

#### REQUIRED-DATA
VM_DATA=("")
VM_AUTOGENERATED_DATA=("VSCODE_PASSKEY" "")


# Load common configs from the common scripts
echo "Load common configs from the common scripts"
source ../lib/common_vm_scripts.sh
vm_creation_steps