#!/bin/bash

# Specific VM template configurations

# PROXMOX
TEMPLATE=5212 # debian 12
VMID=2006 # 3003
TAGS=_dmz,casaos,tools
MACHINE_NAME=CASAOS
START_ON_PVE_REBOOT=1
STORAGE=local-lvm  

# KVM
RAM=8192
CORES=2
BRIDGE=vmbr1
VLAN=20
EXPAND_DISKIMAGE_SIZE=12G # 0G for no resize

#### CLOUD-INIT
IP=192.168.20.6/24 #192.168.30.3
GW=192.168.20.1
DNS=192.168.20.1

#### REQUIRED-DATA
VM_DATA=("")
VM_AUTOGENERATED_DATA=("")


# Load common configs from the common scripts
echo "Load common configs from the common scripts"
source ../lib/common_vm_scripts.sh
vm_creation_steps