#!/bin/bash

# Specific VM template configurations

# Proxmox
TEMPLATE=5006 # debian 12
VMID=1002
TAGS=_dmz,onlyoffice,groupwork
MACHINE_NAME=onlyoffice
START_ON_PVE_REBOOT=1
STORAGE=local-zfs 

# KVM
RAM=12288
CORES=4
BRIDGE=vmbr1
VLAN=10
EXPAND_DISKIMAGE_SIZE=128G # 0G for no resize

#### Cloud Init
IP=192.168.10.2/24
GW=192.168.10.1
DNS=192.168.10.1

#### required data
VM_DATA=()
AUTOGENERATED_DATA=()


# Load common configs from the common scripts
echo "Load common configs from the common scripts"
source ../lib/common_vm_scripts.sh
vm_creation_steps