#!/bin/bash

# Specific VM template configurations

# Proxmox
TEMPLATE=5350 # Vyos 1.5
VMID=102
TAGS=_wan,router,vyos
MACHINE_NAME=VYOS
START_ON_PVE_REBOOT=1
STORAGE=local-lvm 

# KVM
RAM=2048
CORES=1
BRIDGE=vmbr1
VLAN=10
EXPAND_DISKIMAGE_SIZE=0G # 0G for no resize

#### CLOUD-INIT
IP=192.168.10.222/24 
GW=192.168.10.1
DNS=192.168.10.1

#### REQUIRED-DATA
VM_DATA=("")
VM_AUTOGENERATED_DATA=("")


# Load common configs from the common scripts
echo "Load common configs from the common scripts"
source ../lib/common_vm_scripts.sh
vm_creation_steps