#!/bin/bash

# Specific VM template configurations

# Proxmox
TEMPLATE=5006 # Ubuntu 22.04
VMID=3002
TAGS=_vms,coder,dev
MACHINE_NAME=coder
START_ON_PVE_REBOOT=1
STORAGE=local-zfs 

# KVM
RAM=16384
CORES=4
BRIDGE=vmbr1
VLAN=30
EXPAND_DISKIMAGE_SIZE=256G # 0G for no resize

#### CLOUD-INIT
IP=192.168.30.2/24
GW=192.168.30.1
DNS=192.168.30.1

#### REQUIRED-DATA
VM_DATA=("CODER_ACCESS_URL")
VM_AUTOGENERATED_DATA=("")


# Load common configs from the common scripts
echo "Load common configs from the common scripts"
source ../lib/common_vm_scripts.sh
vm_creation_steps